FROM phusion/baseimage:0.11

CMD ["/sbin/my_init"]

# enable ssh password authentication
RUN rm -f /etc/service/sshd/down
RUN sed -i "s/PasswordAuthentication\ *no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
RUN service ssh reload

{{#internet_accessible?}}
EXPOSE 22
{{/internet_accessible?}}

LABEL edu.range.scenario={{instance.scenario.name}}
LABEL edu.range.instance={{instance.name}}


# instance packages

RUN apt-get update
RUN apt-get install -y sudo

{{#instance.packages}}
# installing package {{name}}
RUN apt-get install -y --fix-missing {{name}}
{{/instance.packages}}

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# adds each script to /etc/my_init.d/ which will cause it to be run by /sbin/my_init on container startup.

{{#instance.scripts}}
# installing script {{name}}
COPY {{name}} /etc/my_init.d/{{name}}
RUN chmod +x /etc/my_init.d/{{name}}
{{/instance.scripts}}

